### ISSUE TITLE
Calling dynamic method 'get_keyword_names' failed

### ISSUE THREAD

**Issue by petertilsen** [datakurre/phantomrobot#5]
Just discovered your repo. Wanted to use it, but do run into 

```
Calling dynamic method 'get_keyword_names' failed
```
Searched the net, but couldn't find anything helpful. Any idea?

**Comment by datakurre** [comment]
I haven't run this for years, so I need to find some time to check if this still runs. I gave up a long time ago in favor of Selenium. Yet, this did provide a fun way to control phantomjs even before it got many of its rcurrent features.

Peter Tilsen kirjoitti ti heinäkuuta 28 18:24:41 2015 GMT+0300:

**Comment by petertilsen** [comment]
Thanks for your answer. I have found the issues and fixed em. Will get you a PR

**Comment by datakurre** [comment]
Should have been fixed by @petertilsen in https://github.com/datakurre/phantomrobot/pull/6
